### ISSUE TITLE
Error: ContentDecodingFailed

### ISSUE THREAD

**Issue by pjttrpg** [Raphire/SusAlert#1]
SusAlert no longer works for me as of today and I'm unable to figure out why. Worked fine yesterday, but today this is all the window shows me:

![image](https://user-images.githubusercontent.com/77516302/150076480-04beb3c9-4406-43be-88dc-64ae3e92199c.png)

**Comment by Raphire** [comment]
Hey, this might be an issue with the hosting of the plugin, as I had some reports about that this week. But the plugin seems to be working just fine right now.

If the issue persists for you I would appreciate it if you could check if any errors show up in the dev console, to do this right click anywhere inside the plugin window & click inspect, then go to the console tab.

**Comment by pjttrpg** [comment]
> Hey, this might be an issue with the hosting of the plugin, as I had some reports about that this week. But the plugin seems to be working just fine right now.
> 
> If the issue persists for you I would appreciate it if you could check if any errors show up in the dev console, to do this right click anywhere inside the plugin window & click inspect, then go to the console tab.

Still getting errors and I got this in the dev console:
![image](https://user-images.githubusercontent.com/77516302/150236558-77b03caa-6065-4a12-8e12-8101666f2d38.png)
 I can provide the actual text of the error if necessary, but there is apparently a lot

**Comment by Raphire** [comment]
Huh, thanks for providing this. This seems to be quite an obscure error with chromium, this is the browser that alt1 uses for it's plugins, and it honestly seems like this might be an issue (with your installation of) alt1. Does this happen with any other alt1 plugins? 

You could try to remove the plugin from alt1 and add it again, or reinstalling alt1 all together to see if that fixes things.

**Comment by pjttrpg** [comment]
Reinstalling alt1 entirely seems to have fixed the issue. No other apps on alt1 had this problem in the meantime. Thanks for the help!

**Comment by Raphire** [comment]
Glad to see that the issue was resolved!
