### ISSUE TITLE
HTTP 520 errors during startup of the plugin

### ISSUE THREAD

**Issue by HeercoGrond** [Raphire/SusAlert#8]
Using the Steam RS3 client with Alt1 - I've started getting HTTP520 errors during the launch of the applet which is preventing it from working properly: 

![image](https://user-images.githubusercontent.com/21168987/198602580-4629945a-75dc-4e65-9d56-b1cdee200b5c.png)

More specifically, I think the fact that the 'ImageDetect' isn't working is causing issues with the applet reading the state of the game and what's happening on the screen, which in turn makes it fail to load. Whether this is a library issue, I don't know. 

![image](https://user-images.githubusercontent.com/21168987/198603466-2ee594b0-b573-4e6f-9545-6539a6062de5.png)

![image](https://user-images.githubusercontent.com/21168987/198603999-66396c65-fcc3-46ad-8e7b-e7e51c97f6ed.png)

The applet has the appropriate permissions from Alt1. 

Mind - I am running the game on an UltraWide monitor (3440x1440) but this has so far not been an issue for other applets of the Alt1 Toolkit.

**Comment by HeercoGrond** [comment]
Problem seems to have solved itself.

**Comment by Raphire** [comment]
Thanks for the update, glad it's working! This may've been an issue with the host of a dependency.
